# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}: let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name
    {
      nativeBuildInputs = [zig_0_16];
    }
    ''
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      mkdir "$TMPDIR/src" "$TMPDIR/cache" "$TMPDIR/cache/tmp"
      touch "$TMPDIR/src/build.zig"
      hash="$(cd "$TMPDIR/src" && zig fetch --global-cache-dir "$TMPDIR/cache" ${artifact})"
      mkdir "$out"
      tar zxvf "$TMPDIR/cache/p/$hash.tar.gz" --directory "$out/" --strip-components=1
    '';

  fetchZig = {
    name,
    url,
    hash,
    unpack,
  }: let
    artifact =
      if unpack
      then
        fetchzip {
          inherit url hash;
          nativeBuildInputs = [zstd];
        }
      else fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
  }: let
    parts = lib.splitString "#" url;
    url_base = builtins.elemAt parts 0;
    url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
    rev_base = builtins.elemAt parts 1;
    rev =
      if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null
      then rev_base
      else "refs/heads/${rev_base}";
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    unpack,
  }: let
    parts = lib.splitString "://" url;
    proto = builtins.elemAt parts 0;
    path = builtins.elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig {
        inherit name hash;
        url = "http://${path}";
      };
      "git+https" = fetchGitZig {
        inherit name hash;
        url = "https://${path}";
      };
      http = fetchZig {
        inherit name hash unpack;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash unpack;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
  # The packages, as real directories holding symlinked files, rather than as
  # a farm of symlinked directories.
  #
  # Zig runs a dependency's own build steps with the working directory set to
  # that dependency, and points at the program to run with a path counted in
  # directories up from there. Through a symlink the two disagree: Zig counts
  # from `<farm>/<package>/`, four directories below the root, while the kernel
  # resolves the working directory to `/nix/store/<hash>`, which is three, so
  # the path lands one short of where the program is.
  #
  # It works anyway when the build directory is `/build`, because the sum then
  # overshoots into the root and going above the root stays there. It fails
  # when the build directory is under `/nix/var/nix/builds`, which is where Nix
  # puts it when the sandbox is off. Real directories make the two depths
  # agree, so it works either way.
  #
  # The files have to be real as well, which is the expensive part and cannot
  # be avoided. `--symbolic-link` would leave them pointing into each
  # dependency's own store path, so that the farm is a few megabytes rather
  # than a second copy of every dependency -- but Zig's
  # `installHeadersDirectory` walks the directory and copies only the entries
  # whose kind is `.file`. Symlinked headers are skipped without a word, and
  # the first thing to include one fails with `'dcimgui.h' not found`.
  #
  # `--link` is not the way out. A hard link into a Nix output is a file the
  # builder did not create: inside the Linux sandbox the store is a separate
  # mount and `link` fails with `Invalid cross-device link`, while on Darwin it
  # succeeds and leaves root-owned files in the output, which Nix refuses while
  # canonicalising with `invalid ownership on file`.
  #
  # So it is a real copy, with `--reflink=auto` to share the blocks on a
  # filesystem that can. `nix store optimise` recovers the duplication after
  # the fact, hard-linking identical files across the store, which is the
  # store's own business to do and not a build's.
  copyFarm = farm: entries: pathDependencyPackages:
    runCommandLocal farm
    {
      # The packages whose own manifest declares a dependency by `.path`.
      # Zig 0.16.0 cannot build these through `zig build --system`: it spins
      # in userspace forever, because a `.path` dependency's hash is computed
      # against the system package directory during the fetch and against the
      # real global cache afterwards, and in that mode the two disagree. A
      # package that wants `--system` copies each of these into its build
      # root and passes `--fork=`; see the README.
      passthru = {inherit pathDependencyPackages;};
    }
    ''
      mkdir -p "$out"
      cp --recursive --reflink=auto --dereference --no-preserve=mode \
        ${linkFarm farm entries}/. "$out/"
    '';
in
  copyFarm name [
    {
      name = "aro-0.0.0-JSD1Qk6lNgDdcDV4Vh7Sfy-34m2TluIVOdPzMmj_0BjX";
      path = fetchZigArtifact {
        name = "aro";
        url = "https://github.com/vancluever/arocc/archive/f97cdfc3779aec4b242299e2fc9a1c828c3547c6.tar.gz";
        hash = "sha256-G/NNgk7KhJSLdy17ip1igIzpYhAUlzO7ef8r3/iCv/s=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AANT61wB--nJ95Gj_ctmzAtcjloZ__hRqNw5lC1Kr";
      path = fetchZigArtifact {
        name = "bindings";
        url = "https://deps.files.ghostty.org/DearBindings_v0.17_ImGui_v1.92.5-docking.tar.gz";
        hash = "sha256-i/7FAOAJJvZ5hT7iPWfMOS08MYFzPKRwRzhlHT9wuqM=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AADx3vAHtUVzBYz79RN-jSBg-7vqr82KRG2PDDj3O";
      path = fetchZigArtifact {
        name = "breakpad";
        url = "https://github.com/getsentry/breakpad/archive/25b6b727af49fa383161e7dba4a82ab0661b69b8.tar.gz";
        hash = "sha256-WD8yrJ6iP19GOqQ8xgba1n0tGTjbM2Rcuqx2xh9mzYI=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAOgqbADacob-q2_DMQlmgaG4xKHRuW-6PJ4oJzMZ";
      path = fetchZigArtifact {
        name = "fontconfig";
        url = "https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/2.18.3/fontconfig-2.18.3.tar.xz";
        hash = "sha256-T3tVSjjN94wDP2ZsiHHzdJ4UoJT2Wgf2MMke0LQ9NeM=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAJo-LAHFNfa0p0oMQqmwlBEAZMOeo03azXgrKLTT";
      path = fetchZigArtifact {
        name = "freetype";
        url = "https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.xz";
        hash = "sha256-NrxPHMQTM1No7mVsQq/KZcWjmH6HaMwozxG6d154Wl8=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AALdvswzDmWpxCzd-LJE1C1QZesjzfu0zd2mspjID";
      path = fetchZigArtifact {
        name = "gettext";
        url = "https://ftp.gnu.org/gnu/gettext/gettext-0.26.tar.gz";
        hash = "sha256-Oaz0sDcemxELYABVYqrOWzYx/tmxu57Mz8f1bli7HX8=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAMmpvgL92dJGQdndHv_3KUj32P-C6QWT83-1-lEM";
      path = fetchZigArtifact {
        name = "glslang";
        url = "https://github.com/KhronosGroup/glslang/archive/refs/tags/16.6.0.tar.gz";
        hash = "sha256-nAm5ARSccp33RQV9r6gVJ4qqEBuE0rbhTxakLeUvl/I=";
        unpack = false;
      };
    }
    {
      name = "gobject-0.3.2-Skun7F6HogCMynX2JqeSHS7xr-8pK4ob-qRFIcEasVi3";
      path = fetchZigArtifact {
        name = "gobject";
        url = "https://deps.files.ghostty.org/gobject-2026-07-28-36-1.tar.zst";
        hash = "sha256-dyCfm2XjiAk30zccjD6AgKFBdE7IRsJuoqnscfvnWSQ=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AABZQBQCTF3bl5cdgQ9edw4SCFXPueCYtR6EL9IGu";
      path = fetchZigArtifact {
        name = "gtk4_layer_shell";
        url = "https://github.com/wmww/gtk4-layer-shell/archive/refs/tags/v1.3.0.tar.gz";
        hash = "sha256-HrsBqxTpiv0XJ/aPZJgcN70jMFsfEx9WZ8ArlM9ZMZI=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAAJ_FwYXbjMIdM8T_4Z402GcERnA3uFfjFDuQP4c";
      path = fetchZigArtifact {
        name = "harfbuzz";
        url = "https://github.com/harfbuzz/harfbuzz/releases/download/14.4.0/harfbuzz-14.4.0.tar.xz";
        hash = "sha256-I1ftlmxs7Xv6cgsGQMAjEGWvARWPvqIVCT/6Fa7UQ3E=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAD_MkACxo3rELIYCI7ap_7GsxHN1WH6AsMLDYp6L";
      path = fetchZigArtifact {
        name = "highway";
        url = "https://github.com/google/highway/archive/refs/tags/1.4.0.tar.gz";
        hash = "sha256-5yJBrJUku2U65SztdotQgEXUQ4cmowPxAYGjj3ZKRTw=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI";
      path = fetchZigArtifact {
        name = "imgui";
        url = "https://deps.files.ghostty.org/N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI.tar.gz";
        hash = "sha256-yBbCDox18+Fa6Gc1DnmSVQLRpqhZOLsac7iSfl8x+cs=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAEFmBABuDGOKxAI6VMg41b9euMZ-z7HS9EcUdaor";
      path = fetchZigArtifact {
        name = "iterm2_themes";
        url = "https://deps.files.ghostty.org/ghostty-themes-release-20260831-151010-752a9c0.tgz";
        hash = "sha256-g2U+uDe661v8fVDJG31EdyeW4IwcJDE04Rxe32yNFcU=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAIC5lwAVPJJzxnCAahSvZTIlG-HhtOvnM1uh-66x";
      path = fetchZigArtifact {
        name = "jetbrains_mono";
        url = "https://deps.files.ghostty.org/JetBrainsMono-2.304.tar.gz";
        hash = "sha256-xXppHouCrQmLWWPzlZAy5AOPORCHr3cViFulkEYQXMQ=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAJexYAClrDiJ2R-eT-rfMNK2Qd3--2FRhY7e5nvn";
      path = fetchZigArtifact {
        name = "libpng";
        url = "https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.58.tar.gz";
        hash = "sha256-qdTfRj02puX5wpvW9JZzEtF+mWwYVPNRH4M5JOsZk88=";
        unpack = false;
      };
    }
    {
      name = "libxev-0.0.0-86vtcwIRFADbH4hk-EjROXxlrKIRPQdA41XiTSytYO-F";
      path = fetchZigArtifact {
        name = "libxev";
        url = "https://deps.files.ghostty.org/libxev-9ce8e8e6ff89e583258a7f8e7adeeeaeae8611bf.tar.gz";
        hash = "sha256-fOU1oxIxfoEgoLuWz7fVX6M+zmqpo7gqZObWiH/aDE0=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAH30hwIndEJ9icgSaGo9HFSuUmIv1I6SlorjnfU-";
      path = fetchZigArtifact {
        name = "libxml2";
        url = "https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.4.tar.xz";
        hash = "sha256-mAh/0YHZBwck8/vGXHN32wMDjrkr2II3Ta/0SUATiCE=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAMlwTwAhAtzTNEG7Eg4j7oI33o0_gzLbwDalYZEE";
      path = fetchZigArtifact {
        name = "nerd_fonts_symbols_only";
        url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/NerdFontsSymbolsOnly.tar.xz";
        hash = "sha256-ARcvN9uFQ+2xAuXLXGQQHJ9GhmMIBNSbQZqgeyOmmZY=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAPwCMwB54AUHwsvlixvQkvI1tZ5pRs35ZHfr5Evi";
      path = fetchZigArtifact {
        name = "oniguruma";
        url = "https://github.com/kkos/oniguruma/archive/refs/tags/v6.9.10.tar.gz";
        hash = "sha256-rZIwnQ0T7rwn9lkuh18++/o92iv22llS4A8KISDJIag=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AADYiAAB_80AWnH1AxXC0tql9thT-R-DYO1gBqTLc";
      path = fetchZigArtifact {
        name = "pixels";
        url = "https://deps.files.ghostty.org/pixels-12207ff340169c7d40c570b4b6a97db614fe47e0d83b5801a932dcd44917424c8806.tar.gz";
        hash = "sha256-Veg7FtCRCCUCvxSb9FfzH0IJLFmCZQ4/+657SIcb8Ro=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAKYZBAB-CFHBKs3u4JkeiT4BMvyHu3Y5aaWF3Bbs";
      path = fetchZigArtifact {
        name = "plasma_wayland_protocols";
        url = "https://deps.files.ghostty.org/plasma_wayland_protocols-12207e0851c12acdeee0991e893e0132fc87bb763969a585dc16ecca33e88334c566.tar.gz";
        hash = "sha256-XFi6IUrNjmvKNCbcCLAixGqN2Zeymhs+KLrfccIN9EE=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAKwoawA-G0w_56hQdIqb2ZLoaz064j7PZxgxJhvi";
      path = fetchZigArtifact {
        name = "sentry";
        url = "https://github.com/getsentry/sentry-native/archive/refs/tags/0.16.6.tar.gz";
        hash = "sha256-oZSsQ02hU0cjVWxWKCVnUiCLC2mJ/ue/XtbFs8hHc6s=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAG7ovABenbEcMfcbxnQahv_qPno7CwSPITx-k6RD";
      path = fetchZigArtifact {
        name = "spirv_cross";
        url = "https://github.com/KhronosGroup/SPIRV-Cross/archive/refs/tags/vulkan-sdk-1.4.357.0.tar.gz";
        hash = "sha256-l8kQMmr91E15TOhWEyb6Z1/RlYsnFC8DKVQDBE1jljk=";
        unpack = false;
      };
    }
    {
      name = "translate_c-0.0.0-Q_BUWhVNBwDOEcIqub4VFPJPB6D9dgwzUMHTX5KWr8Xr";
      path = fetchZigArtifact {
        name = "translate_c";
        url = "https://codeberg.org/vancluever/translate-c/archive/4e879eb8aba615de112eabd1231ea6e01920cead.tar.gz";
        hash = "sha256-/sT7W8Kp+O11xaFBgpb/kDiWzfQ0MuXk/d/TuGq1Am8=";
        unpack = true;
      };
    }
    {
      name = "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA";
      path = fetchZigArtifact {
        name = "uucode";
        url = "https://deps.files.ghostty.org/uucode-2826a37a4562284fdacd8fa029d49509cc9bffcd.tar.gz";
        hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
        unpack = true;
      };
    }
    {
      name = "vaxis-0.6.0-BWNV_MjFCQCs9UDHiRkrgw_ayeiPkzOe4xVbaAqXkUWW";
      path = fetchZigArtifact {
        name = "vaxis";
        url = "git+https://github.com/rockorager/libvaxis.git#c1e1f23be38951c425cdf31af455ba23ef178940";
        hash = "sha256-bIXu8lGwGo42QbItC0jOi/eN7u+f4snknBexw7dc0DI=";
        unpack = true;
      };
    }
    {
      name = "vaxis-0.6.0-BWNV_CrbCQCscGpzsAlR402rYQ_tV3aAl081c2iRRkka";
      path = fetchZigArtifact {
        name = "vaxis";
        url = "https://deps.files.ghostty.org/vaxis-1dbbe575dff4586fe51e3217aa5c3fecdcbb6089.tar.gz";
        hash = "sha256-z3J3w+oYapfAZZR+MvWXwg+th1hePDA1TptnKFO4r+M=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAKrHGAAs2shYq8UkE6bGcR1QJtLTyOE_lcosMn6t";
      path = fetchZigArtifact {
        name = "wayland";
        url = "https://deps.files.ghostty.org/wayland-9cb3d7aa9dc995ffafdbdef7ab86a949d0fb0e7d.tar.gz";
        hash = "sha256-6kGR1o5DdnflHzqs3ieCmBAUTpMdOXoyfcYDXiw5xQ0=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA";
      path = fetchZigArtifact {
        name = "wayland_protocols";
        url = "https://deps.files.ghostty.org/N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA.tar.gz";
        hash = "sha256-3S3xSrX0EDgleq7cxLX7msDuAY8/D5SvkJcCjmDTMiM=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAKw-DAAaV8bOAAGqA0-oD7o-HNIlPFYKRXSPT03S";
      path = fetchZigArtifact {
        name = "wayland_protocols";
        url = "https://deps.files.ghostty.org/wayland-protocols-258d8f88f2c8c25a830c6316f87d23ce1a0f12d9.tar.gz";
        hash = "sha256-XO3K3egbdeYPI+XoO13SuOtO+5+Peb16NH0UiusFMPg=";
        unpack = false;
      };
    }
    {
      name = "N-V-__8AAP5JWgCGP_AD0teWpa4krRvE9VPZzvviGdbmN4jI";
      path = fetchZigArtifact {
        name = "wuffs";
        url = "https://deps.files.ghostty.org/wuffs-7411f488fe2e2c205c3d3b3d28638b7356522930.tar.gz";
        hash = "sha256-F4d9NG95iGUdbGLkWy47BchoCaZELF40YSN0sqlxmhw=";
        unpack = false;
      };
    }
    {
      name = "z2d-0.12.1-j5P_Hsw8EQAKyZTQICCQnAH2xYkLDW8k9uefbsYdfPZ-";
      path = fetchZigArtifact {
        name = "z2d";
        url = "https://deps.files.ghostty.org/z2d-7dbae85c81784dba9988320bf9543ed9a81350c8.tar.gz";
        hash = "sha256-Fjr1ORn0ozxU7QY09o2ZOZQHIJsXfVw0UCdZxTKmZJ0=";
        unpack = true;
      };
    }
    {
      name = "zf-0.11.0-OIRy8X-RAAAwaRXHMYpj2uvBnuGTZWEE_3V7acqHQNtW";
      path = fetchZigArtifact {
        name = "zf";
        url = "https://deps.files.ghostty.org/zf-c35c421f84895193246db06c40683c1a30e616ef.tar.gz";
        hash = "sha256-LHurWwqK8jhP8AZd/CXrMJNeVsKftRCTN31/EgEgKaA=";
        unpack = true;
      };
    }
    {
      name = "zig_js-0.0.0-rjCAV7-GAADvMTBL7lPMuvDk7xgS9PCMIZWiOUXLZSlj";
      path = fetchZigArtifact {
        name = "zig_js";
        url = "https://deps.files.ghostty.org/zig_js-3c23860e47fdcdc5af805efb7fd0bdac5fd3e9bc.tar.gz";
        hash = "sha256-Q1643wb/MCX0QkPa9QEY9xeQbqpC2IOrjER0ZyL3mH0=";
        unpack = true;
      };
    }
    {
      name = "zig_objc-0.0.0-Ir_Sp9gsAQCPAJc0oF5xoWePHWP6Y6tCphDeyNUThJoi";
      path = fetchZigArtifact {
        name = "zig_objc";
        url = "https://deps.files.ghostty.org/zig_objc-c8de82ff80281215ad92900866dab7103a8efa8b.tar.gz";
        hash = "sha256-t8cTTJm0crcoGAyOqXO0wB2w7Yit80J2Orwr6prd/G0=";
        unpack = true;
      };
    }
    {
      name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
      path = fetchZigArtifact {
        name = "zig_wayland";
        url = "https://deps.files.ghostty.org/wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX.tar.gz";
        hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
        unpack = true;
      };
    }
    {
      name = "zigimg-0.1.0-8_eo2oyaFwBZwJpmqPkCfVXWBrHcqbYwmrp1I6bTD3lI";
      path = fetchZigArtifact {
        name = "zigimg";
        url = "git+https://github.com/zigimg/zigimg#d695acd97c02e57bb151e8f659d1280f5cd6ca70";
        hash = "sha256-0IYATQldT6eJxRR2T/2CsIYZuzomqjvmdVyjmsjguyE=";
        unpack = true;
      };
    }
    {
      name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
      path = fetchZigArtifact {
        name = "zlib";
        url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
        hash = "sha256-uzKaCizQJ00FUZ1hxmfAYuBpkNcuEl7i36jeZPARnRY=";
        unpack = false;
      };
    }
  ]
  [
  ]
